### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by nikosavola** [CSCfi/singularity-recipes#8]
Hi,

Could you add a LICENSE file to this repository? Namely, I'm wondering if the definition files here may be used as a basis for commercial purposes? I guess definition files are pretty simple but would nevertheless be nice to have a clear policy.

**Comment by mvsjober** [comment]
Hello, 

That's a good idea! Our bad for forgetting to put a license on the repository. I would assume a simple permissive license would do, but I'll confirm with my colleagues first.

**Comment by mvsjober** [comment]
Commit 0fc0e7d67b466b0c6751243b5b71ac72790f2097 adds MIT license
